import { BlockType, ItemType, ItemDef } from '../types';

export const ALL_ITEMS: Record<number, ItemDef> = {
  // Blocks
  [BlockType.GRASS]: {
    id: BlockType.GRASS,
    name: 'Grass Block',
    isBlock: true,
    blockType: BlockType.GRASS,
    color: '#5ead3b',
    category: 'blocks',
  },
  [BlockType.DIRT]: {
    id: BlockType.DIRT,
    name: 'Dirt',
    isBlock: true,
    blockType: BlockType.DIRT,
    color: '#866043',
    category: 'blocks',
  },
  [BlockType.STONE]: {
    id: BlockType.STONE,
    name: 'Stone',
    isBlock: true,
    blockType: BlockType.STONE,
    color: '#7d7d7d',
    category: 'blocks',
  },
  [BlockType.COBBLESTONE]: {
    id: BlockType.COBBLESTONE,
    name: 'Cobblestone',
    isBlock: true,
    blockType: BlockType.COBBLESTONE,
    color: '#686868',
    category: 'blocks',
  },
  [BlockType.OAK_LOG]: {
    id: BlockType.OAK_LOG,
    name: 'Oak Log',
    isBlock: true,
    blockType: BlockType.OAK_LOG,
    color: '#604627',
    category: 'blocks',
  },
  [BlockType.OAK_PLANKS]: {
    id: BlockType.OAK_PLANKS,
    name: 'Oak Planks',
    isBlock: true,
    blockType: BlockType.OAK_PLANKS,
    color: '#b88746',
    category: 'blocks',
  },
  [BlockType.OAK_LEAVES]: {
    id: BlockType.OAK_LEAVES,
    name: 'Oak Leaves',
    isBlock: true,
    blockType: BlockType.OAK_LEAVES,
    color: '#2d6d2d',
    category: 'blocks',
  },
  [BlockType.SAND]: {
    id: BlockType.SAND,
    name: 'Sand',
    isBlock: true,
    blockType: BlockType.SAND,
    color: '#d6cc99',
    category: 'blocks',
  },
  [BlockType.BEDROCK]: {
    id: BlockType.BEDROCK,
    name: 'Bedrock',
    isBlock: true,
    blockType: BlockType.BEDROCK,
    color: '#222222',
    category: 'blocks',
  },
  [BlockType.GLASS]: {
    id: BlockType.GLASS,
    name: 'Glass',
    isBlock: true,
    blockType: BlockType.GLASS,
    color: '#c8e0f0',
    category: 'blocks',
  },
  [BlockType.COAL_ORE]: {
    id: BlockType.COAL_ORE,
    name: 'Coal Ore',
    isBlock: true,
    blockType: BlockType.COAL_ORE,
    color: '#404040',
    category: 'blocks',
  },
  [BlockType.IRON_ORE]: {
    id: BlockType.IRON_ORE,
    name: 'Iron Ore',
    isBlock: true,
    blockType: BlockType.IRON_ORE,
    color: '#d8af93',
    category: 'blocks',
  },
  [BlockType.DIAMOND_ORE]: {
    id: BlockType.DIAMOND_ORE,
    name: 'Diamond Ore',
    isBlock: true,
    blockType: BlockType.DIAMOND_ORE,
    color: '#2cf0ea',
    category: 'blocks',
  },
  [BlockType.BRICK]: {
    id: BlockType.BRICK,
    name: 'Bricks',
    isBlock: true,
    blockType: BlockType.BRICK,
    color: '#a04838',
    category: 'blocks',
  },
  [BlockType.TNT]: {
    id: BlockType.TNT,
    name: 'TNT',
    isBlock: true,
    blockType: BlockType.TNT,
    color: '#db2f22',
    category: 'blocks',
  },
  [BlockType.CRAFTING_TABLE]: {
    id: BlockType.CRAFTING_TABLE,
    name: 'Crafting Table',
    isBlock: true,
    blockType: BlockType.CRAFTING_TABLE,
    color: '#a8753a',
    category: 'blocks',
  },
  [BlockType.FURNACE]: {
    id: BlockType.FURNACE,
    name: 'Furnace',
    isBlock: true,
    blockType: BlockType.FURNACE,
    color: '#656565',
    category: 'blocks',
  },
  [BlockType.CHEST]: {
    id: BlockType.CHEST,
    name: 'Chest',
    isBlock: true,
    blockType: BlockType.CHEST,
    color: '#a06020',
    category: 'blocks',
  },
  [BlockType.BOOKSHELF]: {
    id: BlockType.BOOKSHELF,
    name: 'Bookshelf',
    isBlock: true,
    blockType: BlockType.BOOKSHELF,
    color: '#7b5028',
    category: 'blocks',
  },
  [BlockType.STONE_BRICK]: {
    id: BlockType.STONE_BRICK,
    name: 'Stone Bricks',
    isBlock: true,
    blockType: BlockType.STONE_BRICK,
    color: '#707070',
    category: 'blocks',
  },
  [BlockType.TORCH]: {
    id: BlockType.TORCH,
    name: 'Torch',
    isBlock: true,
    blockType: BlockType.TORCH,
    color: '#ffaa00',
    category: 'blocks',
  },
  [BlockType.GOLD_ORE]: {
    id: BlockType.GOLD_ORE,
    name: 'Gold Ore',
    isBlock: true,
    blockType: BlockType.GOLD_ORE,
    color: '#ecc538',
    category: 'blocks',
  },
  [BlockType.GOLD_BLOCK]: {
    id: BlockType.GOLD_BLOCK,
    name: 'Block of Gold',
    isBlock: true,
    blockType: BlockType.GOLD_BLOCK,
    color: '#f6d132',
    category: 'blocks',
  },
  [BlockType.IRON_BLOCK]: {
    id: BlockType.IRON_BLOCK,
    name: 'Block of Iron',
    isBlock: true,
    blockType: BlockType.IRON_BLOCK,
    color: '#dedede',
    category: 'blocks',
  },
  [BlockType.DIAMOND_BLOCK]: {
    id: BlockType.DIAMOND_BLOCK,
    name: 'Block of Diamond',
    isBlock: true,
    blockType: BlockType.DIAMOND_BLOCK,
    color: '#46e6de',
    category: 'blocks',
  },
  [BlockType.OBSIDIAN]: {
    id: BlockType.OBSIDIAN,
    name: 'Obsidian',
    isBlock: true,
    blockType: BlockType.OBSIDIAN,
    color: '#1a142e',
    category: 'blocks',
  },
  [BlockType.NETHERRACK]: {
    id: BlockType.NETHERRACK,
    name: 'Netherrack',
    isBlock: true,
    blockType: BlockType.NETHERRACK,
    color: '#8b1e1e',
    category: 'blocks',
  },
  [BlockType.SOUL_SAND]: {
    id: BlockType.SOUL_SAND,
    name: 'Soul Sand',
    isBlock: true,
    blockType: BlockType.SOUL_SAND,
    color: '#543d30',
    category: 'blocks',
  },
  [BlockType.GLOWSTONE]: {
    id: BlockType.GLOWSTONE,
    name: 'Glowstone',
    isBlock: true,
    blockType: BlockType.GLOWSTONE,
    color: '#fedb5b',
    category: 'blocks',
  },
  [BlockType.NETHER_BRICK]: {
    id: BlockType.NETHER_BRICK,
    name: 'Nether Bricks',
    isBlock: true,
    blockType: BlockType.NETHER_BRICK,
    color: '#3b1822',
    category: 'blocks',
  },
  [BlockType.NETHER_QUARTZ_ORE]: {
    id: BlockType.NETHER_QUARTZ_ORE,
    name: 'Nether Quartz Ore',
    isBlock: true,
    blockType: BlockType.NETHER_QUARTZ_ORE,
    color: '#923a3a',
    category: 'blocks',
  },
  [BlockType.FIRE]: {
    id: BlockType.FIRE,
    name: 'Fire',
    isBlock: true,
    blockType: BlockType.FIRE,
    color: '#ff8419',
    category: 'blocks',
  },
  [BlockType.LAVA]: {
    id: BlockType.LAVA,
    name: 'Lava',
    isBlock: true,
    blockType: BlockType.LAVA,
    color: '#ff4d00',
    category: 'blocks',
  },
  [BlockType.GRAVEL]: {
    id: BlockType.GRAVEL,
    name: 'Gravel',
    isBlock: true,
    blockType: BlockType.GRAVEL,
    color: '#7a7a7a',
    category: 'blocks',
  },
  [BlockType.QUARTZ_BLOCK]: {
    id: BlockType.QUARTZ_BLOCK,
    name: 'Block of Quartz',
    isBlock: true,
    blockType: BlockType.QUARTZ_BLOCK,
    color: '#eee8e0',
    category: 'blocks',
  },
  [BlockType.CACTUS]: {
    id: BlockType.CACTUS,
    name: 'Cactus',
    isBlock: true,
    blockType: BlockType.CACTUS,
    color: '#2d8a26',
    category: 'blocks',
  },
  [BlockType.SNOW]: {
    id: BlockType.SNOW,
    name: 'Snow Block',
    isBlock: true,
    blockType: BlockType.SNOW,
    color: '#f4faff',
    category: 'blocks',
  },
  [BlockType.SANDSTONE]: {
    id: BlockType.SANDSTONE,
    name: 'Sandstone',
    isBlock: true,
    blockType: BlockType.SANDSTONE,
    color: '#dfd29d',
    category: 'blocks',
  },

  // Materials & Items
  [ItemType.STICK]: {
    id: ItemType.STICK,
    name: 'Stick',
    isBlock: false,
    color: '#8b5a2b',
    category: 'materials',
  },
  [ItemType.COAL]: {
    id: ItemType.COAL,
    name: 'Coal',
    isBlock: false,
    color: '#262626',
    category: 'materials',
  },
  [ItemType.IRON_INGOT]: {
    id: ItemType.IRON_INGOT,
    name: 'Iron Ingot',
    isBlock: false,
    color: '#d8d8d8',
    category: 'materials',
  },
  [ItemType.GOLD_INGOT]: {
    id: ItemType.GOLD_INGOT,
    name: 'Gold Ingot',
    isBlock: false,
    color: '#fcd842',
    category: 'materials',
  },
  [ItemType.DIAMOND]: {
    id: ItemType.DIAMOND,
    name: 'Diamond',
    isBlock: false,
    color: '#4dedf4',
    category: 'materials',
  },
  [ItemType.FLINT]: {
    id: ItemType.FLINT,
    name: 'Flint',
    isBlock: false,
    color: '#343434',
    category: 'materials',
  },
  [ItemType.FLINT_AND_STEEL]: {
    id: ItemType.FLINT_AND_STEEL,
    name: 'Flint and Steel',
    isBlock: false,
    color: '#c2c2c2',
    category: 'tools',
  },
  [ItemType.NETHER_QUARTZ]: {
    id: ItemType.NETHER_QUARTZ,
    name: 'Nether Quartz',
    isBlock: false,
    color: '#f5e8e8',
    category: 'materials',
  },

  // Pickaxes
  [ItemType.WOODEN_PICKAXE]: {
    id: ItemType.WOODEN_PICKAXE,
    name: 'Wooden Pickaxe',
    isBlock: false,
    color: '#b88746',
    category: 'tools',
    miningMultiplier: { stone: 2.0 },
  },
  [ItemType.STONE_PICKAXE]: {
    id: ItemType.STONE_PICKAXE,
    name: 'Stone Pickaxe',
    isBlock: false,
    color: '#888888',
    category: 'tools',
    miningMultiplier: { stone: 3.5 },
  },
  [ItemType.IRON_PICKAXE]: {
    id: ItemType.IRON_PICKAXE,
    name: 'Iron Pickaxe',
    isBlock: false,
    color: '#e4e4e4',
    category: 'tools',
    miningMultiplier: { stone: 6.0 },
  },
  [ItemType.DIAMOND_PICKAXE]: {
    id: ItemType.DIAMOND_PICKAXE,
    name: 'Diamond Pickaxe',
    isBlock: false,
    color: '#43e2dc',
    category: 'tools',
    miningMultiplier: { stone: 10.0 },
  },

  // Swords
  [ItemType.WOODEN_SWORD]: {
    id: ItemType.WOODEN_SWORD,
    name: 'Wooden Sword',
    isBlock: false,
    color: '#b88746',
    category: 'combat',
  },
  [ItemType.STONE_SWORD]: {
    id: ItemType.STONE_SWORD,
    name: 'Stone Sword',
    isBlock: false,
    color: '#888888',
    category: 'combat',
  },
  [ItemType.IRON_SWORD]: {
    id: ItemType.IRON_SWORD,
    name: 'Iron Sword',
    isBlock: false,
    color: '#e4e4e4',
    category: 'combat',
  },
  [ItemType.DIAMOND_SWORD]: {
    id: ItemType.DIAMOND_SWORD,
    name: 'Diamond Sword',
    isBlock: false,
    color: '#43e2dc',
    category: 'combat',
  },

  // Axes
  [ItemType.WOODEN_AXE]: {
    id: ItemType.WOODEN_AXE,
    name: 'Wooden Axe',
    isBlock: false,
    color: '#b88746',
    category: 'tools',
    miningMultiplier: { wood: 2.0 },
  },
  [ItemType.STONE_AXE]: {
    id: ItemType.STONE_AXE,
    name: 'Stone Axe',
    isBlock: false,
    color: '#888888',
    category: 'tools',
    miningMultiplier: { wood: 3.5 },
  },
  [ItemType.IRON_AXE]: {
    id: ItemType.IRON_AXE,
    name: 'Iron Axe',
    isBlock: false,
    color: '#e4e4e4',
    category: 'tools',
    miningMultiplier: { wood: 6.0 },
  },

  // Shovels
  [ItemType.WOODEN_SHOVEL]: {
    id: ItemType.WOODEN_SHOVEL,
    name: 'Wooden Shovel',
    isBlock: false,
    color: '#b88746',
    category: 'tools',
    miningMultiplier: { dirt: 2.0 },
  },
  [ItemType.STONE_SHOVEL]: {
    id: ItemType.STONE_SHOVEL,
    name: 'Stone Shovel',
    isBlock: false,
    color: '#888888',
    category: 'tools',
    miningMultiplier: { dirt: 3.5 },
  },
  [ItemType.IRON_SHOVEL]: {
    id: ItemType.IRON_SHOVEL,
    name: 'Iron Shovel',
    isBlock: false,
    color: '#e4e4e4',
    category: 'tools',
    miningMultiplier: { dirt: 6.0 },
  },

  // Mob Drops & Combat
  [ItemType.ROTTEN_FLESH]: {
    id: ItemType.ROTTEN_FLESH,
    name: 'Rotten Flesh',
    isBlock: false,
    color: '#904e28',
    category: 'materials',
  },
  [ItemType.GUNPOWDER]: {
    id: ItemType.GUNPOWDER,
    name: 'Gunpowder',
    isBlock: false,
    color: '#555555',
    category: 'materials',
  },
  [ItemType.BONE]: {
    id: ItemType.BONE,
    name: 'Bone',
    isBlock: false,
    color: '#eaeaea',
    category: 'materials',
  },
  [ItemType.PORKCHOP]: {
    id: ItemType.PORKCHOP,
    name: 'Raw Porkchop',
    isBlock: false,
    color: '#e07d7d',
    category: 'materials',
  },
  [ItemType.ARROW]: {
    id: ItemType.ARROW,
    name: 'Arrow',
    isBlock: false,
    color: '#d0d0d0',
    category: 'combat',
  },
  [ItemType.BOW]: {
    id: ItemType.BOW,
    name: 'Bow',
    isBlock: false,
    color: '#8b5a2b',
    category: 'combat',
  },
  [ItemType.GOLD_NUGGET]: {
    id: ItemType.GOLD_NUGGET,
    name: 'Gold Nugget',
    isBlock: false,
    color: '#ffd700',
    category: 'materials',
  },
  [ItemType.PORTAL_BUILDER]: {
    id: ItemType.PORTAL_BUILDER,
    name: 'Auto Nether Portal Builder',
    isBlock: false,
    color: '#9932CC', // Deep Purple
    category: 'tools',
  },
  [BlockType.END_STONE]: {
    id: BlockType.END_STONE,
    name: 'End Stone',
    isBlock: true,
    blockType: BlockType.END_STONE,
    color: '#deeaac',
    category: 'blocks',
  },
  [BlockType.END_PORTAL_FRAME]: {
    id: BlockType.END_PORTAL_FRAME,
    name: 'End Portal Frame',
    isBlock: true,
    blockType: BlockType.END_PORTAL_FRAME,
    color: '#345e54',
    category: 'blocks',
  },
  [ItemType.END_PORTAL_BUILDER]: {
    id: ItemType.END_PORTAL_BUILDER,
    name: 'Auto End Portal Builder',
    isBlock: false,
    color: '#00FA9A', // Medium Spring Green
    category: 'tools',
  },
};

export function getItemDef(id: number): ItemDef {
  return (
    ALL_ITEMS[id] || {
      id,
      name: 'Unknown Item',
      isBlock: false,
      color: '#888',
      category: 'materials',
    }
  );
}
